# Generated by Django 5.0.4 on 2024-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedtrack',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='likedtrack',
            name='duration_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likedtrack',
            name='artist_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='likedtrack',
            name='track_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='likedtrack',
            name='track_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='likedtrack',
            name='track_name',
            field=models.CharField(max_length=255),
        ),
    ]
