# Generated by Django 5.0.4 on 2024-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedSong',
        ),
    ]
